version: '3.3'
services:
  fpm:
    image: sitdh/php-fpm:latest 
    volumes:
      - ./aloha-app:/var/www/html
    networks:
      - aloha
    expose: 
      - "9000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/logs
      - ./aloha-app:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - aloha

  db:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./datasource/property_data.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: aloha
      MYSQL_DATABASE: aloha
      MYSQL_USER: aloha
      MSYQL_PASSWORD: aloha
    depends_on:
      - fpm
    networks:
      - aloha

networks:
  aloha:
