version: '3.3'
services:
  fpm:
    image: sitdh/php-fpm:latest 
    volumes:
      - ./aloha-app:/var/www/html
    networks:
      - aloha
    expose: 
      - "9000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/logs
      - ./aloha-app:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - aloha

  db:
    build: ./datasource
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: guava
      MYSQL_DATABASE: guava
      MYSQL_USER: guava
      MSYQL_PASSWORD: guava
    depends_on:
      - fpm
    networks:
      - aloha
    ports:
      - 3306:3306

networks:
  aloha:
